version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        restart: unless-stopped
